#!/bin/bash

set -eu

SCHEMACHAIN_HOME=${BASH_SOURCE%/*}/src

source "${SCHEMACHAIN_HOME}/migrations.incl.bash"
source "${SCHEMACHAIN_HOME}/repo.incl.bash"
source "${SCHEMACHAIN_HOME}/schema.incl.bash"
source "${SCHEMACHAIN_HOME}/postgres.incl.bash"
source "${SCHEMACHAIN_HOME}/cmd_help.incl.bash"
source "${SCHEMACHAIN_HOME}/cmd_check.incl.bash"
source "${SCHEMACHAIN_HOME}/cmd_generate.incl.bash"
source "${SCHEMACHAIN_HOME}/dispatch.incl.bash"

dispatch_command $@
